name: Ensure Required Files Exist

on:
  push:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for required files
        run: |
          missing=0
          for file in reflektion.txt frågor.txt; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              missing=1
            else
              echo "✅ Found file: $file"
            fi
          done
          if [ $missing -ne 0 ]; then
            echo "🚨 One or more required files are missing."
            exit 1
          fi
